apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        - --source=ingress
        - --domain-filter=k8s.xyz
        - --provider=google
        - --google-project=<project-id>
        - --registry=txt
        - --txt-owner-id=my-identifier
        ###Below section is for openshift cluster
        #env:
        #- name: GOOGLE_APPLICATION_CREDENTIALS
        #  value: /etc/secrets/service-account/credentials.json
        #volumeMounts:
        #- mountPath: /etc/secrets/service-account/
        #  name: google-service-account
      #volumes:
      #- name: google-service-account
      #  secret:
      #    defaultMode: 420
      #    items:
      #    - key: credentials.json
      #      path: credentials.json
      #    secretName: google-service-account